version: "3.7"
services:
  batfish:
    image: batfish/batfish:latest
    container_name: batfish
    volumes:
      - ./mynetworks/example_network:/notebooks/mynetworks/example_network
    network_mode: host
